export const properties = [
    {
      id: "1",
      title: "Modern Luxury Villa with Ocean View",
      location: "123 Coastal Drive, Malibu, CA",
      price: 2750000,
      beds: 4,
      baths: 3.5,
      sqft: 3200,
      lat: 34.0522,
      lng: -118.2437,
      image: "/luxury-modern-house-exterior.png",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Swimming Pool", "Garden", "Garage", "Modern Kitchen"],
      yearBuilt: 2019,
    },
    {
      id: "2",
      title: "Contemporary Beach House",
      location: "456 Ocean View Dr, Malibu, CA",
      price: 2450000,
      beds: 3,
      baths: 2.5,
      sqft: 2800,
      image: "/modern-beach-house.png",
      lat: 34.0522,
      lng: -118.2437,
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Swimming Pool", "Garden", "Garage"],
      yearBuilt: 2020,
    },
    {
      id: "3",
      title: "Luxury Downtown Penthouse",
      location: "789 Skyline Ave, Los Angeles, CA",
      price: 12000,
      beds: 2,
      baths: 2,
      sqft: 1800,
      image: "/modern-ocean-living.png",
      status: "For Rent",
      statusColor: "bg-blue-600 hover:bg-blue-700",
      features: ["Fitness Center", "High-Speed Internet", "Modern Kitchen"],
      yearBuilt: 2018,
    },
    {
      id: "4",
      title: "Spacious Family Home with Garden",
      location: "234 Maple Street, Beverly Hills, CA",
      price: 3200000,
      beds: 5,
      baths: 4,
      sqft: 4200,
      lat: 34.0522,
      lng: -118.2437,
      image: "/luxury-master-bedroom.png",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Garden", "Garage", "Modern Kitchen"],
      yearBuilt: 2015,
    },
    {
      id: "5",
      title: "Modern Apartment in City Center",
      location: "567 Downtown Blvd, Los Angeles, CA",
      price: 8500,
      beds: 2,
      baths: 2,
      sqft: 1500,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=modern-apartment",
      status: "For Rent",
      statusColor: "bg-blue-600 hover:bg-blue-700",
      features: ["Fitness Center", "High-Speed Internet"],
      yearBuilt: 2019,
    },
    {
      id: "6",
      title: "Charming Cottage with Mountain View",
      location: "890 Highland Drive, Santa Monica, CA",
      price: 1850000,
      beds: 3,
      baths: 2,
      sqft: 1950,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=mountain-cottage",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Garden", "Modern Kitchen"],
      yearBuilt: 2010,
    },
    {
      id: "7",
      title: "Luxury Waterfront Estate",
      location: "123 Bayshore Drive, Newport Beach, CA",
      price: 5750000,
      beds: 6,
      baths: 5.5,
      sqft: 6500,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=waterfront-estate",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Swimming Pool", "Garden", "Garage", "Modern Kitchen"],
      yearBuilt: 2017,
    },
    {
      id: "8",
      title: "Modern Studio in Arts District",
      location: "456 Creative Lane, Los Angeles, CA",
      price: 3200,
      beds: 0,
      baths: 1,
      sqft: 750,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=modern-studio",
      status: "For Rent",
      statusColor: "bg-blue-600 hover:bg-blue-700",
      features: ["High-Speed Internet", "Modern Kitchen"],
      yearBuilt: 2020,
    },
    {
      id: "9",
      title: "Elegant Victorian Home",
      location: "789 Heritage Ave, Pasadena, CA",
      price: 2950000,
      beds: 4,
      baths: 3,
      sqft: 3800,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=victorian-home",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Garden", "Garage"],
      yearBuilt: 1910,
    },
    {
      id: "10",
      title: "Cozy Loft with City Views",
      location: "101 Downtown View, Los Angeles, CA",
      price: 4500,
      beds: 1,
      baths: 1.5,
      sqft: 1100,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=city-loft",
      status: "For Rent",
      statusColor: "bg-blue-600 hover:bg-blue-700",
      features: ["High-Speed Internet", "Modern Kitchen"],
      yearBuilt: 2016,
    },
    {
      id: "11",
      title: "Mediterranean Villa with Pool",
      location: "202 Sunset Blvd, Malibu, CA",
      price: 4250000,
      beds: 5,
      baths: 4.5,
      sqft: 4800,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=mediterranean-villa",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Swimming Pool", "Garden", "Garage", "Modern Kitchen"],
      yearBuilt: 2012,
    },
    {
      id: "12",
      title: "Luxury High-Rise Condo",
      location: "303 Skyview Tower, Los Angeles, CA",
      price: 1950000,
      beds: 2,
      baths: 2,
      sqft: 1650,
      lat: 34.0522,
      lng: -118.2437,
      image: "/placeholder.svg?key=highrise-condo",
      status: "For Sale",
      statusColor: "bg-green-600 hover:bg-green-700",
      features: ["Fitness Center", "High-Speed Internet", "Modern Kitchen"],
      yearBuilt: 2018,
    },
  ]
  